name: workflow for PR merge
on:
  pull_request:
    branches:
      - main
    types:
      - closed

jobs:
  merge-workflow-job:
    name: job for PR merge
    if: ${{ github.event.pull_request.merged }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: dump github context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"

      - name: dump contents of file
        run: cat ${{ github.workspace }}/contents.txt

      - name: dump contents of second file
        run: cat ${{ github.workspace }}/second.txt      