name: workflow for release
on:
  release:
    types: [published]

env:
  TAG_TO_RELEASE: ${{ github.event.release.tag_name }}    

jobs:
  release-workflow-job:
    name: job for release
    runs-on: ubuntu-latest 
    steps:
      - uses: actions/checkout@v2

      - name: dump github context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
          RELEASE_TAG: ${{ github.event.release.tag_name }}
        run: |
          echo "$GITHUB_CONTEXT"

      - name: separator
        run: |
          echo "set from top of job: $TAG_TO_RELEASE"  